name: Sonarcloud

on:
  push:
    branches:
      - main
      - develop
      - feature/*
  pull_request:
      types: [openned, syncronize]
      


jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        with:
          sonarcloud-organization: santiago9779
          sonarcloud-project-key: santiago9779
